"""add_remediation_ai_fields

Revision ID: 160b97e09194
Revises: f6a7b8c9d0e1
Create Date: 2026-03-08 03:47:15.984236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '160b97e09194'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('temporary_mitigation', sa.String(), nullable=True))
    op.add_column('remediations', sa.Column('permanent_fix_summary', sa.String(), nullable=True))
    op.add_column('remediations', sa.Column('review_note', sa.String(), nullable=True))
    op.add_column('remediations', sa.Column('senior_review_urgency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediations', 'senior_review_urgency')
    op.drop_column('remediations', 'review_note')
    op.drop_column('remediations', 'permanent_fix_summary')
    op.drop_column('remediations', 'temporary_mitigation')
    # ### end Alembic commands ###
