"""add_urgency_and_analysis_source_to_analyses

Revision ID: 185481a4c338
Revises: 265311b7a697
Create Date: 2026-03-07 21:02:59.610987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '185481a4c338'
down_revision: Union[str, None] = '265311b7a697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('urgency', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('analysis_source', sa.String(), nullable=False, server_default='backboard_ai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'analysis_source')
    op.drop_column('analyses', 'urgency')
    # ### end Alembic commands ###
