"""initial_schema

Revision ID: 265311b7a697
Revises: 
Create Date: 2026-03-07 19:48:25.099797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '265311b7a697'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('backboard_assistant_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_agent', sa.String(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_id'), 'scan_runs', ['id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_id'), 'dependencies', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('vuln_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('osv_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('business_impact', sa.String(), nullable=False),
    sa.Column('recommended_fix', sa.String(), nullable=False),
    sa.Column('backboard_thread_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('safe_version', sa.String(), nullable=True),
    sa.Column('install_command', sa.String(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    op.create_table('usage_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=True),
    sa.Column('context_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_locations_id'), 'usage_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_locations_id'), table_name='usage_locations')
    op.drop_table('usage_locations')
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_dependencies_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_scan_runs_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
